In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
mainloc='/content/drive/My Drive/Research/ABSA_Final/'
mainloc

'/content/drive/My Drive/Research/ABSA_Final/'

In [ ]:
import pandas as pd 
import numpy as np 
from nltk.tokenize import word_tokenize
import re
from nltk.corpus import wordnet
import pandas as pd 
import numpy as np 
from nltk.tokenize import word_tokenize
import re
from sklearn.base import BaseEstimator, TransformerMixin
from nltk.corpus import wordnet
import pandas as pd 
import numpy as np 
import string
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('treebank')
from nltk.tag import UnigramTagger
from nltk.corpus import treebank
import pandas as pd 
import numpy as np 
import string
from gensim.test.utils import common_texts, get_tmpfile
from gensim.models import Word2Vec
#import fasttext
import gensim
from gensim.test.utils import datapath
from gensim.models import KeyedVectors
import seaborn as sns 
import re  # For preprocessing
from time import time  # To time our operations
from collections import defaultdict  # For word frequency
import spacy  # For preprocessing
import logging  # Setting up the loggings to monitor gensim
logging.basicConfig(format="%(levelname)s - %(asctime)s: %(message)s", datefmt= '%H:%M:%S', level=logging.INFO)
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag, word_tokenize
from nltk.corpus import stopwords
from collections import Counter

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Package treebank is already up-to-date!


In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
class CleanText(BaseEstimator, TransformerMixin):
    
    def setContractions(self,contractions):
        self.contractions=contractions 
  
    def setStop_singlish(self,stop_singlish):
        self.stop_singlish=stop_singlish
        
    def setLem(self,lemCln):
        self.lemCln=lemCln
        
    def setremnum(self,remnum):
        self.remnum=remnum
            
    def remove_mentions(self, input_text):
        return re.sub(r'@\w+', '', input_text)
    
    def remove_urls(self, input_text):
        return re.sub(r'http.?://[^\s]+[\s]?', '', input_text)
    
    def remove_email(self,input_text):
        return re.sub(r'[\w\.-]+@[\w\.-]+','',input_text)
    
    def remove_hash(self,input_text):
        return re.sub(r'(?<=#)\w+','',input_text)
    
    def remove_time(self,input_text):
        return re.sub(r'(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]','',input_text)
    
    def remove_float(self,input_text):
        return re.sub("\d*\.\d+","",input_text)
        
    def remove_phoneno(self,input_text):
        y= re.sub(r"\b\d{5}\b",'',input_text)
        y= re.sub(r"\b\d{4}\b",'',y)
        y= re.sub(r"\b\d{6}\b",'',y)
        y= re.sub(r"\b\d{7}\b",'',y)
        y= re.sub(r"\b\d{8}\b",'',y)
        y= re.sub(r"\b\d{9}\b",'',y)
        y= re.sub(r"\b\d{10}\b",'',y)
        y= re.sub(r"\b\d{11}\b",'',y)
        y= re.sub(r"\b\d{12}\b",'',y)
        y= re.sub(r"\b\d{13}\b",'',y)
        y= re.sub(r"\b\d{14}\b",'',y)
        y= re.sub(r"\b\d{15}\b",'',y)
        y= re.sub(r"\b\d{16}\b",'',y)
        y= re.sub(r"\b\d{17}\b",'',y)
        y= re.sub(r"\b\d{18}\b",'',y)
        y= re.sub(r"\b\d{19}\b",'',y)
        y= re.sub(r"\b\d{20}\b",'',y)
        return y 
        
    def remove_year(self,input_text):
        return re.sub(r"\b(19[40][0-9]|20[0-1][0-9]|2020)\b",'',input_text)
     
    def remove_emoji(self, input_text):
        emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
        return emoji_pattern.sub(r'', input_text)
    
    def apostrophe(self,input_text):
        words = input_text.split()
        for word in words:
            if word.lower() in self.contractions:
                input_text = input_text.replace(word, self.contractions[word.lower()])
        return input_text
    
    def spell_check(self,input_text):
        input_text=str(input_text)
        spell = SpellChecker()
        words = input_text.split() 
        spellcheck_words = [spell.correction(word) for word in words] 
        return " ".join(spellcheck_words) 

    def remove_punctuation(self, input_text):
        temp=re.sub("[!#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]+",' ',input_text).strip()
        output_text=' '.join(temp.split())
        return output_text
       
    def remove_singlewords(self,input_text):
        return ' '.join( [w for w in input_text.split() if len(w)>1] )
        
    def remove_digits(self, input_text):
        return re.sub('\d+', '', input_text)
    
    def to_lower(self, input_text):
        return str(input_text).lower()
    
    def remove_stop_singlish(self, input_text):
        words = input_text.split() 
        clean_words = [word for word in words if (word not in self.stop_singlish)] 
        return " ".join(clean_words) 
    
    def remove_stop_numbers(self,input_text):
        words=input_text.split()
        clean_words = [word for word in words if (word not in self.remnum)] 
        return " ".join(clean_words) 
    
    def remove_stopwords(self, input_text):
        stopwords_list = stopwords.words('english')
        words = input_text.split() 
        slist= stopwords_list
        clean_words = [word for word in words if (word not in slist) and len(word) > 1] 
        return " ".join(clean_words) 
    
    def lemmetzing(self,input_text):
        wnl = WordNetLemmatizer() 
        words = input_text.split() 
        lem=[]
        for word,tag in pos_tag(word_tokenize(input_text)):
            wntag=tag[0].lower()
            wntag = wntag if wntag in ['a', 'r', 'n', 'v'] else None
            if not wntag:
                lemma=word
                lem.append(lemma)
            else:
                lemma=wnl.lemmatize(word,wntag)
                lem.append(lemma)
        
        return " ".join(lem) 
    
    def lemmetize_sin(self,input_text):
        vec=[]
        words=input_text.split()
        for x in range(len(words)):
            if(words[x] in list(self.lemCln.original)):
                ind=self.lemCln[self.lemCln['original']==words[x]]['subs'].index.values.astype(int)[0]
                w=self.lemCln[self.lemCln['original']==words[x]]['subs'][ind]
                vec.append(w)   
            else:
                w=words[x]
                vec.append(w)
        vec1=' '.join(vec)
        return vec1
    
    def seperate_numwords(self,input_text):
        words=input_text.split()
        output=''
        for word in words:
            temp = re.compile("([0-9]+)([a-zA-Z]+)") 
            if temp.match(word) and len(word)>2:
                res = temp.match(word).groups() 
                output=output+' '+ ' '.join(res).strip()
            else:
                output=output+' '+word
        output= ' '.join(output.split())
        return output.strip()
    
    def remove_zerostartwords(self,input_text):
        #temp=re.sub(r'\b0\d{2}\b',' ',input_text).strip()
        output= " ".join(filter(lambda x:x[0]!='0', input_text.split()))
        return output 
    
    def fit(self, X, y=None, **fit_params):
        return self

    def transform(self, X, **transform_params):
        clean_txt = X.apply(self.to_lower).apply(self.apostrophe).apply(self.remove_urls).apply(self.remove_email)\
        .apply(self.remove_emoji).apply(self.remove_hash).apply(self.remove_year)\
        .apply(self.remove_mentions).apply(self.remove_time).apply(self.remove_punctuation).apply(self.remove_phoneno)\
        .apply(self.remove_float).apply(self.seperate_numwords).apply(self.remove_zerostartwords).apply(self.remove_phoneno)\
        .apply(self.remove_stop_numbers).apply(self.remove_stop_singlish).apply(self.lemmetzing).apply(self.lemmetize_sin)
        return clean_txt
      
def readTxtFile(loc):
    s = open(loc, 'r').read()
    whip = eval(s)
    return whip

def lemFile(loc):
    lem=pd.read_csv(loc,header=None,index_col=None)
    lem.columns=['original','subs']
    lem=lem.dropna()
    lem=lem.drop_duplicates()
    a=lem.groupby('original').count().reset_index()
    lis=a[a['subs']>1].original.unique()
    lemCln=lem[~(lem['original'].isin(lis))]
    return lemCln

def stopfile(loc):
    swords=pd.read_csv(loc,header=None)
    swords.columns=['sword']
    swords=list(swords.dropna()['sword'])
    return swords

In [ ]:
df=pd.read_csv(mainloc+"data.csv")
df.columns=['id','comment','network','billing_price','package','customer_service','data','service_product','sentiment']
df=df[~df['sentiment'].isna()]
df=df.fillna(0)


In [ ]:
#Network 
df.loc[df['network']=='0', 'network'] = 0
df.loc[df['network']=='1', 'network'] = 1
df.network.unique()

array([0, 1], dtype=object)

In [ ]:
#Billing_price 
df.billing_price.unique()
df.loc[df['billing_price']=='0', 'billing_price'] = 0
df.loc[df['billing_price']=='1', 'billing_price'] = 1
df.loc[df['billing_price']=='2', 'billing_price'] = 1
df.loc[df['billing_price']==' ', 'billing_price'] = 1
df.billing_price.unique()

array([0, 1], dtype=object)

In [ ]:
#Customer service 
df.customer_service.unique()
df.loc[df['customer_service']=='0', 'customer_service'] = 0
df.loc[df['customer_service']=='1', 'customer_service'] = 1
df.loc[df['customer_service']=='   ', 'customer_service'] = 1
df.customer_service.unique()

array([1, 0], dtype=object)

In [ ]:
#Sentiment 
df.sentiment.unique()

df.loc[df['sentiment']=='0', 'sentiment'] = 0
df.loc[df['sentiment']=='1', 'sentiment'] = 1
df.loc[df['sentiment']=='2', 'sentiment'] = -1
df.loc[df['sentiment']=='-11', 'sentiment'] = -1
df.loc[df['sentiment']=='1-', 'sentiment'] = -1
df.loc[df['sentiment']=='10', 'sentiment'] = -1
df.loc[df['sentiment']=='-1', 'sentiment'] = -1
df.sentiment.unique()

array([0, 1, -1], dtype=object)

In [ ]:
df['id']=df['id'].astype(int)
df['network']=df['network'].astype(int)
df['billing_price']=df['billing_price'].astype(int)
df['package']=df['package'].astype(int)
df['customer_service']=df['customer_service'].astype(int)
df['data']=df['data'].astype(int)
df['service_product']=df['service_product'].astype(int)
df['sentiment']=df['sentiment'].astype(int)
print("size of dataframe: ", df.shape[0])
df.head(2)

size of dataframe:  10060


id  ... sentiment
0  125940  ...         0
1   61803  ...         0

[2 rows x 9 columns]

In [ ]:
#Witholut lemetize sinhala and populating it to cleanAnswer
t = time()

contracloc=mainloc+"Helper_Files/Contractions.txt"
stopdigitloc = mainloc+'Helper_Files/datacln.xlsx'
lemloc=mainloc+"Helper_Files/lemmatization_singlish.csv"

contractions= readTxtFile(contracloc)

#Extract stop values related to digits 
stop_digit= pd.read_excel(stopdigitloc)
stop_digit['word']=stop_digit['word'].astype(str)
remnum=stop_digit[(stop_digit['isdigit']==True) & (stop_digit['freq']<=10)]
remnum=list(remnum.word)

#Extract stop value related to singlish 
stop_singlish=stop_digit[stop_digit['Stopflag']==1]
stop_singlish=list(stop_singlish.word)

#Extract lemmatization related to singlish
lemcln=lemFile(lemloc)

ct = CleanText()
ct.setStop_singlish(stop_singlish)
ct.setContractions(contractions)
ct.setremnum(remnum)
ct.setLem(lemcln)
sr_clean = ct.fit_transform(df.comment)
df['cleanAnswer1']=sr_clean

print('Time to clean up everything: {} mins'.format(round((time() - t) / 60, 2)))

Time to clean up everything: 0.76 mins


In [ ]:
def token(x):
    y=word_tokenize(x.cleanAnswer)
    return y 

def nwords(x):
    y=len(x.tokens)
    return y 

def englishWordsPerc(x):
    words=x.cleanAnswer.split()
    if(len(words)>0):
        l=len([word for word in words if (wordnet.synsets(word))])
        perc=100-(l/len(words))*100
        return perc
    else:
        return 0
    
df['tokens']=df.apply(token,axis=1)
df['nwords']=df.apply(nwords,axis=1)
df['singperc']=df.apply(englishWordsPerc,axis=1)
df['comment_len']= df['cleanAnswer'].apply(lambda x:len(x))
df.head(2)

id  ... comment_len
0  125940  ...        1648
1   61803  ...        1372

[2 rows x 15 columns]

In [ ]:
df.to_csv(mainloc+"df_train.csv",index=False)